name: "📚 문서화 요청"
description: "문서 작성 또는 수정이 필요한 부분을 제안해주세요."
title: "[📚 Docs] "
labels: "📚 Docs"
body:
  - type: input
    attributes:
      label: 📍 문서 위치
      placeholder: ex) README, API 명세서, GitHub Wiki
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📝 요청 내용
      description: 어떤 내용을 문서화해야 하는지 작성해주세요.
      placeholder: |
        - API 응답 형식 변경 사항 정리
        - 로그인/회원가입 흐름 명세 추가
        - Swagger 문서 최신화
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📌 참고할 내용
      description: 관련 코드, 이슈, 노션 문서 등 참고자료가 있다면 남겨주세요.
      placeholder: |
        - 관련 커밋 링크
        - API 스펙 변경 내용
        - 디자인 시안

  - type: textarea
    attributes:
      label: 🙋🏻 덧붙일 말
      description: 팀에게 추가로 전달하고 싶은 말이 있다면 자유롭게 작성해주세요.