name: Notion Report on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  notion:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Install tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
      - name: Detect Notion title property
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          DB_JSON=$(curl -sS -X GET "https://api.notion.com/v1/databases/${NOTION_DATABASE_ID}" \
            -H "Authorization: Bearer ${NOTION_TOKEN}" \
            -H "Notion-Version: 2022-06-28")
          TITLE_PROP=$(echo "$DB_JSON" | jq -r '.properties | to_entries[] | select(.value.type=="title") | .key')
          if [ -z "$TITLE_PROP" ] || [ "$TITLE_PROP" = "null" ]; then
            TITLE_PROP="Name"
          fi
          echo "TITLE_PROP=$TITLE_PROP" >> $GITHUB_ENV
      - name: Create Notion Page
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          REPO: ${{ github.repository }}
          LABELS_JSON: ${{ toJson(github.event.pull_request.labels) }}
          MERGED_AT: ${{ github.event.pull_request.merged_at }}
        run: |
          # Labels -> Multi-select 배열 변환
          LABELS=$(echo "$LABELS_JSON" | jq -r '[.[].name]')
          # Summary 기본값
          SUMMARY="자동 기록: $PR_TITLE"
          
          # Area 기본값: AI
          # - 필요 시 'Frontend' 또는 'Spring'으로 변경하세요.
          # - 라벨 기반 자동 설정으로 바꾸려면 이후에 AREA 계산 로직을 추가하면 됩니다.
          AREA="AI"

          curl -sS -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer ${NOTION_TOKEN}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data @- <<EOF
          {
            "parent": { "database_id": "${NOTION_DATABASE_ID}" },
            "properties": {
              "${TITLE_PROP}": {
                "title": [{ "text": { "content": "${PR_TITLE}" } }]
              },
              "Status": {
                "select": { "name": "Merged" }
              },
              "State": {
                "select": { "name": "처리 전" }
              },
              "Area": {
                "select": { "name": "${AREA}" }
              },
              "PR": {
                "url": "${PR_URL}"
              },
              "Repo": {
                "rich_text": [{ "text": { "content": "${REPO}" } }]
              },
              "MergedAt": {
                "date": { "start": "${MERGED_AT}" }
              },
              "Labels": {
                "multi_select": $(echo "$LABELS" | jq -c '[.[] | { "name": . }]')
              },
              "Summary": {
                "rich_text": [{ "text": { "content": "${SUMMARY}" } }]
              }
            }
          }
          EOF
      - name: Ensure Notion DB schema
        run: |
          curl -sS -X PATCH "https://api.notion.com/v1/databases/${{ secrets.NOTION_DATABASE_ID }}" \
            -H "Authorization: Bearer ${{ secrets.NOTION_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data '{
              "properties": {
                "Status": { "select": { "options": [{ "name": "Merged" }] } },
                "State": { "select": { "options": [{ "name": "처리 전" }, { "name": "처리 완료" }] } },
                "Area": { "select": { "options": [
                  { "name": "AI" },
                  { "name": "Frontend" },
                  { "name": "Spring" },
                  { "name": "미분류" }
                ] } },
                "PR": { "url": {} },
                "Repo": { "rich_text": {} },
                "MergedAt": { "date": {} },
                "Labels": { "multi_select": {} },
                "Summary": { "rich_text": {} }
              }
            }'