name: Sync main to fork

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: false

      # 혹시 남아있을 수도 있는 이전 extraheader/remote를 제거
      - name: Clear any leftover auth and remotes
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true
          git remote remove fork || true

      - name: Add fork remote with Fine-grained PAT
        run: |
          git remote add fork https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/chan000518/bubblog-FE.git

      - name: Sanity check token access
        run: |
          # (테스트 용) 접근 가능하면 해시 목록이 출력됨. 실패하면 exit 2로 중단
          git ls-remote fork || { echo "Token cannot access fork"; exit 2; }

      - name: Push main (safer force)
        run: |
          git push --force-with-lease fork main
