name: Sync main to fork

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: false  # 포크 푸시에 다른 토큰 쓸 예정

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add fork remote
        run: |
          git remote add fork https://chan000518:${{ secrets.REPO_TOKEN }}@github.com/chan000518/bubblog-FE.git

      - name: Push main branch to fork
        run: |
          git push --force-with-lease fork main
